### ISSUE TITLE
Provide some warning of how much space install-kali will require

### ISSUE THREAD

**Issue by nk9** [stevemcilwain/quiver#1]
I just ran install-kali.sh on a VM with a bit of space left (I'm not sure exactly how much, unfortunately). It ate up everything and then all the commands started failing with "No space left on device."

The command does warn you something like "this command does a LOT", but it doesn't say how much space is needed for everything. Which seems to be many hundreds of megabytes, if not more. It would be very helpful if this were made explicit. Even better, the script should ballpark the amount of space required and then give you a warning before running if you're going to have less than some amount of space left on your VM when it's through.

**Comment by stevemcilwain** [comment]
Yeah, that script is really my personal setup and includes a LOT of extra tools and repos. I have some ideas on how to include setup of Quiver dependencies in much more modular fashion.

**Comment by stevemcilwain** [comment]
I removed the install-kali.sh script, it contained way more than what's needed for Quiver.  Instead, just follow the instructions to git clone the repo and edit/source .zshrc.  Once loaded you can use 
```
qq-install
```
This will install only the needed packages and repos.

**Comment by nk9** [comment]
That's excellent, thank you!
