### ISSUE TITLE
Suggestion: modules/qq-srv.zsh

### ISSUE THREAD

**Issue by fullstackpotato** [stevemcilwain/quiver#22]
**Problem:**
It is very rare that I want to share anything other than my serving folder (`/srv`) as I take time to organise tools/scripts and so forth into deliberate folders. e.g. `linux/shell/..` or `windows/post/..` or `engagement/id/..` (to name just three).

**Solution:**
[`pushd / popd`](https://en.wikipedia.org/wiki/Pushd_and_popd) work well here to temporarily move directory from where you are to host, and then flop back so you don't have to remember or type anything in (yes I am that lazy!). Ftp/Tftp could also benefit from this style of temporarily moving into the folder.

Note: I use a non-root account hence the need for sudo.

```bash
# if no port is passed, they will run on port 80
qq-srv-web() {
    if [ "$#" -eq  "1" ]
    then
        pushd /srv; sudo python3 -m http.server $1; popd;
    else
        pushd /srv; sudo python3 -m http.server 80; popd;
    fi
}
qq-srv-php() {
    if [ "$#" -eq  "1" ]
    then
        pushd /srv; sudo php -S 0.0.0.0:$1; popd;
    else
        pushd /srv; sudo php -S 0.0.0.0:80; popd;
    fi
}
```

**Comment by fullstackpotato** [comment]
**Update:**
Totally forgot about this last night, but a candidate to replace python's simple http server would be `updog` (https://github.com/sc0tfree/updog).
In addition to sharing the folder, it can handle ssl with `--ssl`, has built in gui to handle uploading of files in the browser and the option to password protect the web server. 

I've been trying it out on my current engagement and found it to be very handy and quicker to sort than an nginx docker with self signed certs.

**Comment by stevemcilwain** [comment]
I left the existing qq-srv functions as-is and added these as qq-srv-web-auto, qq-srv-php-auto.  But I also added aliases for them to srv-web, srv-php.  Updog looks great, I also added that to qq-install and qq-srv.
