### ISSUE TITLE
Bugs: qq-enum-web-dirs.zsh and output of SSL commands

### ISSUE THREAD

**Issue by fullstackpotato** [stevemcilwain/quiver#26]
Bugs Encountered:
- Thread count on tools within `qq-enum-web-dirs.zsh` are set to 1 and very low.
- The output command is doing the recursive problem from issue #25, this is happening with `qq-ssl-testssl*`. Not sure if it's present in any other tools.

**Comment by stevemcilwain** [comment]
I use thread count of 1 by default to avoid getting IP bans by bug bounty targets.  I can make this a prompt that you specify or possibly a setting somewhere for "aggression".   I'll look into the recursive thing, but I think I already fixed this? What version are using?  If not v0.16.1 then try qq-update and see if you can reproduce it.

**Comment by fullstackpotato** [comment]
Sorry, took a while to get back to this. Can confirm that the 0.16.1 fixes this :)
