### ISSUE TITLE
help for my setting

### ISSUE THREAD

**Issue by saberzaid** [stevemcilwain/quiver#27]
thank you for this great plugin 

i run kali using my cusom zsh and i have managed to add quiver plugin in my custom setting 

im login as user in kali , and the error when i run most of the command in qq :

WORDLIST: /usr/share/seclists/Discovery/Web-Content/quickhits.txt
OUTPUT: /home 
mkdir: cannot create directory ‘/hosts’: Permission denied

is there away to give Permission  auto in quiver plugins as user ?

**Comment by stevemcilwain** [comment]
Hi, quiver is running within your shell as the use you are logged in with. In the case above you're setting OUTPUT to the /home directory which usually requires root permissions.  Instead try using /home/<username> which you should have permissions to your own home directory.
