### ISSUE TITLE
kali linux

### ISSUE THREAD

**Issue by saberzaid** [stevemcilwain/quiver#29]
thanks for your support

another problem i notice , after instllation i can run the tool fine but i did not excute the command qq-install 

if i run the qq-install it will start install the python2 etc that is not supported in kali anymore and keep gettig error msg , im trying this with the latest kali version also up to date

but if i not run the qq-install i still can see the scripts and run some quiver tools such as nmap etc

**Comment by nk9** [comment]
Can you provide the error message you’re seeing? I’m using it successfully on the latest kali after running `qq-install`.

**Comment by saberzaid** [comment]
hello thanks for the replay 

well as you know kali linux not using pip anymore , they using now pip3 , mine is fresh kali updated install  i found those error durring the qq-install 


/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
+ n@6.5.1
added 1 package from 4 contributors in 5.548s
/usr/local/bin/eslint -> /usr/local/lib/node_modules/eslint/bin/eslint.js
+ eslint@6.8.0
added 134 packages from 84 contributors in 19.363s
[*] Installing python packages... 
sudo: pip: command not found
sudo: pip: command not found
sudo: pip: command not found



Cloning into '/opt/enum/LinkFinder'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 583 (delta 0), reused 0 (delta 0), pack-reused 580
Receiving objects: 100% (583/583), 1.09 MiB | 931.00 KiB/s, done.
Resolving deltas: 100% (281/281), done.
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
[*] Installation completed 



Cloning into '/opt/enum/S3Scanner'...
remote: Enumerating objects: 266, done.
remote: Counting objects: 100% (266/266), done.
remote: Compressing objects: 100% (159/159), done.
remote: Total 955 (delta 158), reused 192 (delta 97), pack-reused 689
Receiving objects: 100% (955/955), 201.13 KiB | 410.00 KiB/s, done.
Resolving deltas: 100% (547/547), done.
sudo: pip: command not found
~
fatal: destination path '/opt/recon/knock' already exists and is not an empty directory.
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    from setuptools import setup
ImportError: No module named setuptools




~
Cloning into '/opt/recon/knock'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1292 (delta 0), reused 1 (delta 0), pack-reused 1289
Receiving objects: 100% (1292/1292), 379.18 KiB | 389.00 KiB/s, done.
Resolving deltas: 100% (572/572), done.
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    from setuptools import setup
ImportError: No module named setuptools



i did also make sure the setuptools is installed and it is becouse its via pip3 , but the qq-install using the old pip 

↳ sudo pip3 install setuptools
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (44.0.0)

**Comment by saberzaid** [comment]
im login as user btw ,

**Comment by stevemcilwain** [comment]
I've update everything to use pip3 and python3 compatible tools only.  Coming shortly in the 1.0 release.
