### ISSUE TITLE
Adjusting default masscan ports

### ISSUE THREAD

**Issue by nk9** [stevemcilwain/quiver#3]
Hi Steve. I'd like to change the ports which quiver sends to masscan by default. I can see where the current list is, in `qq-enum-network:35`. But I'm wondering: should I edit this list and push it back? Or would you prefer a PR which defines a list of ports to be added to this default list?

The ports I'm considering adding are for databases. MongoDB (27017), SQL Server (1433), Oracle (1521).

**Comment by stevemcilwain** [comment]
That's an easy change, I'll add them and push it to MASTER to then you can just qq-update.

**Comment by stevemcilwain** [comment]
Done.

**Comment by nk9** [comment]
Thanks Steve!
