### ISSUE TITLE
Kali linux wifi adapter issue

### ISSUE THREAD

**Issue by Abgfaba** [stevemcilwain/quiver#30]
Hello guys, i am a noob in linux and in using terminal but i want to start penetration testing and etc. So the problem is the following, i am using mac OS Catalina and  i want to use an external adapter tp-link wn722n v2 as a device for monitor mode and scanning around, but to connect the external device to the laptop i use a dongle, and so i connect the adapter to the dongle and the dongle to the laptop. I got Virtualbox and network is on NAT ( all of the settings are on default) i added the device but it does not show as tp link wn722n but as realtek 802.11n NIC. when the adapter is connected it does not light up even when its on the host, how i can make it work on the kali linux distribution ?

**Comment by stevemcilwain** [comment]
Hi @Abgfaba, these issues are just for Quiver, a ZSH plugin designed for Kali. I can't really help you with your wifi issue, but suggest you try posting in a forum such as: 

https://www.reddit.com/r/Kalilinux/

Good luck!
