### ISSUE TITLE
Suggestion: qq-notes-search

### ISSUE THREAD

**Issue by fullstackpotato** [stevemcilwain/quiver#31]
**File**: `qq-notes.zsh`
**Function**: `__notes()`

I'm not sure if it's the way I have my notes or if it's an issue that has happened for others. I was having problems searching for a note where I'd made a mention to a specific technology within the file, but that was not part of the filename so I had to fall back to `grep`.
Would it be possible to change the `ls/grep` combo in this function to a purely grep based one to search not only the titles but also the contents?

Line 16 (currently):
```bash
select note in $(ls -R --file-type ${__NOTES} | grep -ie ".md$" | grep -i "$1")
```

Line 16 (suggested):
```bash
select note in $(grep -rli "$1" *.md)
```

I believe the output should be identical in terms of formatting, but will likely need a quick test.

**Comment by fullstackpotato** [comment]
I went into a little bit more of a deep dive on this and found a much more visual/interactive way of searching through notes on the cli. Ideal if you use tmux and run a separate tab to read/search markdown based notes.

You can type what you want to search and let it do it's magic to simplify the list. Useful for notes in the format that you have in your secrets repo (https://github.com/stevemcilwain/secrets).
This idea was taken from the tool https://github.com/srid/neuron, the moment I saw the searching and reading of notes I knew I had to replicate this as it was exactly what I wanted.

**Tools required**:
- fzf (https://github.com/junegunn/fzf) - `sudo apt-get install fzf`
- bat (https://github.com/sharkdp/bat) - download dpkg from releases, not an ideal installation method although there may be a more efficient way of this. I am not a smart man.
- ripgrep (https://github.com/BurntSushi/ripgrep) - `sudo apt-get install ripgrep`

**Code**:
```sh
rg --no-heading --no-line-number --with-filename --color=always --sort path -m1 "" ${__NOTES}/*.md | fzf --tac --no-sort -d ':' --ansi --preview-window wrap --preview 'bat --style=plain --color=always ${1}'
```

**Screenshot**:
![image](https://user-images.githubusercontent.com/23582311/80634351-45ba2580-8a52-11ea-8eff-cc26bdb9b78a.png)

**Comment by stevemcilwain** [comment]
I am doing both great suggestions. Fixing qq-notes and qq-notes-search and adding qq-notes-menu with your ripgrep/fzf/bat suggestion. Very cool, thanks! Will be in next release, 0.17, hopefully today or by this weekend.

**Comment by stevemcilwain** [comment]
For your first suggestion, how about also use -w with grep to search by whole word? I think that would result in less false positives and make the search more useful/practical?

**Comment by fullstackpotato** [comment]
Yeah that sounds like a good idea, admittedly I was getting too many returns with some searches. So that would solve it 😄

**Comment by fullstackpotato** [comment]
Thought I'd help out with this by learning from my mistakes (I make many!). If you reference as it is above, the window will show the full path. Better option is to fall in line with how you've done it in other functions with `cd XYZ` + `cd -`

```bash
qq-notes-menu() {
  # prob insert the logic from the function __NOTES() in qq-notes.zsh?

  cd ${__NOTES}
  rg --no-heading --no-line-number --with-filename --color=always --sort path -m1 "" *.md | fzf --tac --no-sort -d ':' --ansi --preview-window wrap --preview 'bat --style=plain --color=always ${1}'
  cd -
}
```
