### ISSUE TITLE
Completion of qq commands without intermediate words

### ISSUE THREAD

**Issue by nk9** [stevemcilwain/quiver#4]
I find myself using things like `qq-enum-networks-masscan` but having trouble remembering exactly the set of words to go between `qq` and `masscan`. Equally, there are commands for the same program which are in different categories (e.g. `qq-enum-web-screens-eyewitness` vs `qq-recon-screens-by-file-eyewitness`). While the different categories make sense, it can be tough remembering exactly which options are available.

What would be ideal is if I could provide a bit of the command get a list of the relevant options. Example:

```
$ qq-eye<Tab>
qq-enum-web-screens-eyewitness		qq-recon-screens-by-file-eyewitness
qq-recon-screens-by-file-eyewitness
```

and then tab to each one in turn.

I have taken a look at [how zsh does completion](http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Completion-System) and I am wondering if the right approach would be to use `_multi_parts` with the `-i` flag:

> The `-i` option causes `_multi_parts` to insert a unique match even if that requires multiple separators to be inserted. This is not usually the expected behaviour with filenames, but certain other types of completion, for example those with a fixed set of possibilities, may be more suited to this form.

There is also a regex method which I haven't explored yet.

Anyway, I wanted to ask about this and make sure you agreed it was a good idea. And then to see if you already have thoughts. Or maybe I'm doing it wrong, or it's a super simple change. But I'm happy to explore a solution if you don't have one in mind already.

**Comment by stevemcilwain** [comment]
Anything that makes it easier and faster to use!  I appreciate you taking the time to research the solution, let me know what you figure out.  I can add you as a contributor and then just make a "dev-" branch so we can both try it out.  Thanks!

**Comment by nk9** [comment]
Sounds good, I'll let you know when I have something to share.

**Comment by nk9** [comment]
So this is going to work. Working out the details now, but if you want to try it out you just need to add this to the `quiver.plugin.zsh` file:

```
zstyle ':completion:*' matcher-list 'r:|[-]=**'
```

**Comment by stevemcilwain** [comment]
Yeah, I like the search benefit... but sometimes it actually makes it harder to auto-complete where I want to go.  I have also tried peppering in aliases for common-used functions... but that seems a little chaotic.  

I tried to read up on zstyle but it gave me a headache instantly - so kudos to figuring this out @nk9 !

I'll play with it some more.

**Comment by nk9** [comment]
OK, try setting this in the same place instead:

```
ZSTYLE_ORIG=`zstyle -L ':completion:\*' matcher-list`
ZSTYLE_NEW="${ZSTYLE_ORIG} 'r:|[-]=**'"
eval ${ZSTYLE_NEW}
```

Instead of overwriting the original rules, this just appends the new rule. This should mean that the standard auto-completion behavior won't change until the initial rules fail.

**Comment by stevemcilwain** [comment]
Works great!  Thanks, I'll include this in the next merge.
