### ISSUE TITLE
Personalisation 

### ISSUE THREAD

**Issue by fullstackpotato** [stevemcilwain/quiver#6]
Hey, first of all thank you for putting this out there for us all to benefit from it. It's so much more of an elegant solution than the numerous aliases I was rolling with.

I want to fully adopt this and fold in some of my aliases that are very specific to how I work, such as creating engagement folders for my day job and tasks to interact with internal tools. However I've been having a hard time keeping up with the updates and keeping my additions in the script. 

How best would you suggest that I tackle this? I was thinking of producing my own `qq-custom.zsh` module to house my personalisation pieces. But I'm unsure if this will conflict with any future changes/additions that you're planning down the road.

**Comment by stevemcilwain** [comment]
Thanks for the thanks! 

Good question, when I started this project I didn't really think of it as something others would use, but am now trying to better accommodate that by working on a dev branch and recording basic release notes.  Let's try qq-custom.zsh.  I need to merge and release my 0.9 branch today and I'll include a .gitignore for qq-custom.zsh.  You can put anything specific to you there and it won't be committed to the repo.  

If there's anything you want to add that is not private or proprietary then I'd be very happy to incorporate those changes.  For example if you have different nmap scans or scaffolding out engagement folders.  Just add one or more issues here.  

In 0.9 I've added a .quiver folder that contains a log of the loading process.  So after you add stuff to qq-custom.zsh you can check .quiver/log.txt to look for any errors when loading the plugin.

**Comment by stevemcilwain** [comment]
OK @zneedotdev I have added modules/qq-custom.zsh to the .gitignore file.  I merged this in with a set of changes I made in the Dev-0.9 branch (see RELEASES.md).  You can add qq-custom to the modules directory and it will be loaded up.

In the meantime, I'll think about a more elegant solution if it's not too complex.  Thanks!

**Comment by fullstackpotato** [comment]
Np at all, you've done some fantastic work. I'd be more than happy to drop in some bits and pieces I have written. I'll chip away and find the bits I find useful, then I'll add issues as I go. It'll likely be a slower process than I'd ideally like due to my upcoming schedule :(

That is brilliant thank you, that will make it more manageable for me.
